
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: wishpond_rails_development

test:
  <<: *default
  database: wishpond_rails_test

production:
  <<: *default
  database: wishpond_rails_production
  username: wishpond_rails
  password: <%= ENV['WISHPOND_RAILS_DATABASE_PASSWORD'] %>
